import { Server, Swords, Factory, PawPrint, Leaf, Sprout, Sword, Zap, Users, Crosshair, Shield, Globe, Skull, Flame, Wrench, Bird, TreePine, Cpu, Brain, Boxes, Rocket, Map, Axe } from 'lucide-react';

export const ADAPTER_ICONS: Record<string, React.FC<{ className?: string }>> = {
  valheim:               Sword,
  minecraft:             Swords,
  satisfactory:          Factory,
  palworld:              PawPrint,
  eco:                   Leaf,
  enshrouded:            Sprout,
  riftbreaker:           Zap,
  'among-us':            Users,
  dota2:                 Crosshair,
  'counter-strike-2':    Shield,
  dayz:                  Skull,
  terraria:              Globe,
  rust:                  Flame,
  'team-fortress-2':     Wrench,
  'garrys-mod':          Cpu,
  'ark-survival-ascended': Bird,
  'dont-starve-together': TreePine,
  'project-zomboid':     Brain,
  '7-days-to-die':       Axe,
  'left-4-dead-2':       Boxes,
  factorio:              Map,
  'risk-of-rain-2':      Rocket,
  squad:                 Crosshair,
  'conan-exiles':        Sword,
  default:               Server,
};

export const ADAPTER_NAMES: Record<string, string> = {
  valheim:               'Valheim',
  minecraft:             'Minecraft',
  satisfactory:          'Satisfactory',
  palworld:              'Palworld',
  eco:                   'Eco',
  enshrouded:            'Enshrouded',
  riftbreaker:           'The Riftbreaker',
  'among-us':            'Among Us',
  dota2:                 'Dota 2',
  'counter-strike-2':    'Counter-Strike 2',
  dayz:                  'DayZ',
  terraria:              'Terraria',
  rust:                  'Rust',
  'team-fortress-2':     'Team Fortress 2',
  'garrys-mod':          "Garry's Mod",
  'ark-survival-ascended': 'ARK: Survival Ascended',
  'dont-starve-together': "Don't Starve Together",
  'project-zomboid':     'Project Zomboid',
  '7-days-to-die':       '7 Days to Die',
  'left-4-dead-2':       'Left 4 Dead 2',
  factorio:              'Factorio',
  'risk-of-rain-2':      'Risk of Rain 2',
  squad:                 'Squad',
  'conan-exiles':        'Conan Exiles',
};

// Which deploy methods each adapter supports (mirrors manifest.yaml deploy_methods)
export const ADAPTER_DEPLOY_METHODS: Record<string, string[]> = {
  'valheim':               ['steamcmd', 'manual', 'docker'],
  'minecraft':             ['manual', 'docker'],
  'satisfactory':          ['steamcmd', 'manual'],
  'palworld':              ['steamcmd', 'manual'],
  'eco':                   ['steamcmd', 'manual'],
  'enshrouded':            ['steamcmd', 'manual'],
  'riftbreaker':           ['manual'],
  'among-us':              ['manual', 'docker'],
  'dota2':                 ['steamcmd', 'docker'],
  'counter-strike-2':      ['steamcmd', 'docker'],
  'dayz':                  ['steamcmd', 'docker'],
  'terraria':              ['manual', 'docker'],
  'rust':                  ['steamcmd', 'docker'],
  'team-fortress-2':       ['steamcmd', 'docker'],
  'garrys-mod':            ['steamcmd', 'docker'],
  'ark-survival-ascended': ['steamcmd', 'docker'],
  'dont-starve-together':  ['steamcmd', 'docker'],
  'project-zomboid':       ['steamcmd', 'docker'],
  '7-days-to-die':         ['steamcmd', 'docker'],
  'left-4-dead-2':         ['steamcmd', 'docker'],
  'factorio':              ['manual', 'steamcmd', 'docker'],
  'risk-of-rain-2':        ['steamcmd', 'docker'],
  'squad':                 ['steamcmd', 'docker'],
  'conan-exiles':          ['steamcmd', 'docker'],
};

export const ADAPTER_COLORS: Record<string, string> = {
  valheim:               '#4a90d9',
  minecraft:             '#5c8a3c',
  satisfactory:          '#f5a623',
  palworld:              '#7b68ee',
  eco:                   '#4caf50',
  enshrouded:            '#9c7c4a',
  riftbreaker:           '#e74c3c',
  'among-us':            '#c62828',
  dota2:                 '#b71c1c',
  'counter-strike-2':    '#f9a825',
  dayz:                  '#4e342e',
  terraria:              '#558b2f',
  rust:                  '#bf360c',
  'team-fortress-2':     '#cc3d00',
  'garrys-mod':          '#1565c0',
  'ark-survival-ascended': '#00838f',
  'dont-starve-together': '#4a2c00',
  'project-zomboid':     '#2e7d32',
  '7-days-to-die':       '#6a1b9a',
  'left-4-dead-2':       '#c62828',
  factorio:              '#e65100',
  'risk-of-rain-2':      '#1a237e',
  squad:                 '#33691e',
  'conan-exiles':        '#795548',
};
